import fs from "node:fs";
import path from "node:path";

/**
 * hmem configuration — loaded from hmem.config.json in the project directory.
 * All values have sensible defaults; the config file is optional.
 *
 * Place hmem.config.json in HMEM_PROJECT_DIR (next to your .hmem files).
 *
 * ## Character limits
 *
 * Option A — just set the two endpoints, levels in between are interpolated linearly:
 * {
 *   "maxL1Chars": 500,
 *   "maxLnChars": 50000
 * }
 *
 * Option B — specify all levels explicitly:
 * {
 *   "maxCharsPerLevel": [500, 5000, 15000, 30000, 50000]
 * }
 *
 * Option A and B can be combined; explicit array takes precedence.
 *
 */

export interface HmemConfig {
  /**
   * Max characters per level, indexed by depth (0=L1, 1=L2, …, maxDepth-1=Ln).
   * Computed from maxL1Chars + maxLnChars via linear interpolation if not set explicitly.
   */
  maxCharsPerLevel: number[];
  /** Max tree depth (1 = L1 only, 5 = full depth). Default: 5 */
  maxDepth: number;
  /** Max entries returned by a default bulk read(). Default: 100 */
  defaultReadLimit: number;
  /**
   * Memory category prefixes. Keys are single uppercase letters, values are human-readable names.
   * Default: P=Project, L=Lesson, T=Task, E=Error, D=Decision, M=Milestone, S=Skill, N=Navigator.
   * Users can add custom prefixes (e.g. "R": "Research") in hmem.config.json.
   */
  prefixes: Record<string, string>;
  /**
   * Number of top-accessed entries that are automatically promoted to L2 depth in bulk reads.
   * These are entries with the highest access_count (excluding zero) — "organic favorites".
   * Set to 0 to disable. Default: 5.
   */
  accessCountTopN: number;
  /**
   * Descriptions for prefix category headers (X0000 entries).
   * Used as L1 text for abstract header entries in grouped bulk reads.
   * Users can override or add descriptions in hmem.config.json.
   */
  prefixDescriptions: Record<string, string>;
  /**
   * Max characters for auto-extracted titles. Default: 30.
   * Titles are short labels for navigation (like chapter titles in a book).
   */
  maxTitleChars: number;
  /**
   * V2 bulk-read algorithm tuning parameters.
   * Controls how many entries receive expanded treatment in default reads.
   */
  bulkReadV2: {
    /** Number of top-accessed entries to expand — legacy fixed fallback (default: 3) */
    topAccessCount: number;
    /** Number of newest entries to expand — legacy fixed fallback (default: 5) */
    topNewestCount: number;
    /** Number of obsolete entries to keep visible (default: 3) */
    topObsoleteCount: number;
    /** Number of entries with the most sub-nodes to always expand (default: 3) */
    topSubnodeCount: number;
    /** Percentage-based selection (overrides fixed counts when set) */
    newestPercent?: number;
    newestMin?: number;
    newestMax?: number;
    accessPercent?: number;
    accessMin?: number;
    accessMax?: number;
  };
  /** Sync configuration (present only in unified config format). */
  sync?: SyncConfigBlock;
}

export interface SyncConfigBlock {
  serverUrl: string;
  userId: string;
  salt: string;
  token?: string;
  syncSecrets?: boolean;
  lastPushAt?: string | null;
  lastPullAt?: string | null;
}

export const DEFAULT_PREFIXES: Record<string, string> = {
  P: "Project",
  L: "Lesson",
  T: "Task",
  E: "Error",
  D: "Decision",
  M: "Milestone",
  S: "Skill",
  N: "Navigator",
  H: "Human",
  R: "Rule",
  O: "Original",
  I: "Infrastructure",
};

/**
 * Default descriptions for prefix category headers (X0000 entries).
 * These are used as L1 text for abstract header entries that group
 * entries by category in bulk reads.
 */
export const DEFAULT_PREFIX_DESCRIPTIONS: Record<string, string> = {
  P: "(P)roject experiences and summaries",
  L: "(L)essons learned and best practices",
  T: "(T)asks and work items",
  E: "(E)rrors encountered and their fixes",
  D: "(D)ecisions and their rationale",
  M: "(M)ilestones and achievements",
  S: "(S)kills and technical knowledge",
  N: "(N)avigation and context notes",
  H: "(H)uman — knowledge about the user",
  R: "(R)ules — user-defined rules and constraints",
  O: "(O)riginal context — raw session history with progressive summarization (auto-generated by flush_context)",
  I: "(I)nfrastructure — devices, servers, deployments, network. Active device = the one the agent runs on.",
};

export const DEFAULT_CONFIG: HmemConfig = {
  maxCharsPerLevel: [200, 2_500, 10_000, 25_000, 50_000],
  maxDepth: 5,
  defaultReadLimit: 100,
  prefixes: { ...DEFAULT_PREFIXES },
  maxTitleChars: 50,
  accessCountTopN: 5,
  prefixDescriptions: { ...DEFAULT_PREFIX_DESCRIPTIONS },
  bulkReadV2: {
    topAccessCount: 3,
    topNewestCount: 5,
    topObsoleteCount: 3,
    topSubnodeCount: 3,
    newestPercent: 20,
    newestMin: 5,
    newestMax: 15,
    accessPercent: 10,
    accessMin: 3,
    accessMax: 8,
  },
};

/**
 * Format prefix map as "P=Project, L=Lesson, ..." for tool descriptions.
 */
export function formatPrefixList(prefixes: Record<string, string>): string {
  return Object.entries(prefixes).map(([k, v]) => `${k}=${v}`).join(", ");
}

/**
 * Compute a linearly interpolated char-limit array between l1 and ln for `depth` levels.
 * depth=1 → [l1], depth=2 → [l1, ln], depth=5 → [l1, …, ln]
 */
export function linearLimits(l1: number, ln: number, depth: number): number[] {
  if (depth <= 1) return [l1];
  return Array.from({ length: depth }, (_, i) =>
    Math.round(l1 + (ln - l1) * (i / (depth - 1)))
  );
}

/**
 * Save hmem.config.json in the unified format.
 * Writes maxCharsPerLevel directly (no reverse-computing maxL1Chars/maxLnChars).
 * If a sync token is present, the file is chmod 600 for security.
 */
export function saveHmemConfig(projectDir: string, config: HmemConfig): void {
  const configPath = path.join(projectDir, "hmem.config.json");

  const output: Record<string, unknown> = {
    memory: {
      maxCharsPerLevel: config.maxCharsPerLevel,
      maxDepth: config.maxDepth,
      defaultReadLimit: config.defaultReadLimit,
      maxTitleChars: config.maxTitleChars,
      accessCountTopN: config.accessCountTopN,
      prefixes: config.prefixes,
      prefixDescriptions: config.prefixDescriptions,
      bulkReadV2: config.bulkReadV2,
    },
  };

  if (config.sync) {
    output.sync = config.sync;
  }

  fs.writeFileSync(configPath, JSON.stringify(output, null, 2), "utf-8");

  // Secure file if token is present
  if (config.sync?.token) {
    try { fs.chmodSync(configPath, 0o600); } catch {}
  }
}

/** Known memory config keys — used to detect unified vs flat format. */
const MEMORY_KEYS = new Set(["maxL1Chars", "maxLnChars", "maxCharsPerLevel", "maxDepth",
  "defaultReadLimit", "prefixes", "prefixDescriptions", "bulkReadV2", "maxTitleChars", "accessCountTopN"]);

/**
 * Load hmem.config.json from projectDir.
 * Unknown keys are ignored. Missing keys fall back to defaults.
 */
export function loadHmemConfig(projectDir: string): HmemConfig {
  const configPath = path.join(projectDir, "hmem.config.json");
  if (!fs.existsSync(configPath)) {
    return { ...DEFAULT_CONFIG, prefixes: { ...DEFAULT_PREFIXES }, prefixDescriptions: { ...DEFAULT_PREFIX_DESCRIPTIONS }, bulkReadV2: { ...DEFAULT_CONFIG.bulkReadV2 } };
  }

  try {
    const raw = JSON.parse(fs.readFileSync(configPath, "utf-8"));

    // Detect unified vs legacy (flat) format.
    // Unified: { memory: { <known keys> }, sync?: { ... } }
    // Legacy:  { maxL1Chars: 200, ... } (memory settings at top level)
    const isUnified = raw.memory && typeof raw.memory === "object"
      && !Array.isArray(raw.memory)
      && Object.keys(raw.memory).some((k: string) => MEMORY_KEYS.has(k));
    const memoryRaw = isUnified ? raw.memory : raw;
    const syncRaw = raw.sync && typeof raw.sync === "object" && !Array.isArray(raw.sync) ? raw.sync : undefined;

    const cfg: HmemConfig = {
      ...DEFAULT_CONFIG,
      prefixDescriptions: { ...DEFAULT_PREFIX_DESCRIPTIONS },
      bulkReadV2: { ...DEFAULT_CONFIG.bulkReadV2 },
    };

    if (typeof memoryRaw.maxDepth === "number" && memoryRaw.maxDepth >= 1 && memoryRaw.maxDepth <= 10) cfg.maxDepth = memoryRaw.maxDepth;
    if (typeof memoryRaw.defaultReadLimit === "number" && memoryRaw.defaultReadLimit > 0) cfg.defaultReadLimit = memoryRaw.defaultReadLimit;
    if (typeof memoryRaw.accessCountTopN === "number" && memoryRaw.accessCountTopN >= 0) cfg.accessCountTopN = memoryRaw.accessCountTopN;
    if (typeof memoryRaw.maxTitleChars === "number" && memoryRaw.maxTitleChars >= 10 && memoryRaw.maxTitleChars <= 120) cfg.maxTitleChars = memoryRaw.maxTitleChars;

    // Prefixes: merge user-defined with defaults (user can override or add)
    if (memoryRaw.prefixes && typeof memoryRaw.prefixes === "object" && !Array.isArray(memoryRaw.prefixes)) {
      const merged = { ...DEFAULT_PREFIXES };
      for (const [key, val] of Object.entries(memoryRaw.prefixes)) {
        if (typeof key === "string" && /^[A-Z]$/.test(key) && typeof val === "string" && val.length > 0) {
          merged[key] = val;
        }
      }
      cfg.prefixes = merged;
    }

    // Prefix descriptions: merge user-defined with defaults
    if (memoryRaw.prefixDescriptions && typeof memoryRaw.prefixDescriptions === "object" && !Array.isArray(memoryRaw.prefixDescriptions)) {
      for (const [key, val] of Object.entries(memoryRaw.prefixDescriptions)) {
        if (typeof key === "string" && /^[A-Z]$/.test(key) && typeof val === "string" && val.length > 0) {
          cfg.prefixDescriptions[key] = val;
        }
      }
    }
    // Also generate descriptions for any new user prefixes that lack descriptions
    for (const key of Object.keys(cfg.prefixes)) {
      if (!cfg.prefixDescriptions[key]) {
        cfg.prefixDescriptions[key] = cfg.prefixes[key];
      }
    }

    // V2 bulk-read tuning
    if (memoryRaw.bulkReadV2 && typeof memoryRaw.bulkReadV2 === "object") {
      const v2 = memoryRaw.bulkReadV2;
      if (typeof v2.topAccessCount === "number" && v2.topAccessCount >= 0) cfg.bulkReadV2.topAccessCount = v2.topAccessCount;
      if (typeof v2.topNewestCount === "number" && v2.topNewestCount >= 0) cfg.bulkReadV2.topNewestCount = v2.topNewestCount;
      if (typeof v2.topObsoleteCount === "number" && v2.topObsoleteCount >= 0) cfg.bulkReadV2.topObsoleteCount = v2.topObsoleteCount;
      if (typeof v2.topSubnodeCount === "number" && v2.topSubnodeCount >= 0) cfg.bulkReadV2.topSubnodeCount = v2.topSubnodeCount;
      // Percentage-based selection
      if (typeof v2.newestPercent === "number" && v2.newestPercent > 0) cfg.bulkReadV2.newestPercent = v2.newestPercent;
      if (typeof v2.newestMin === "number" && v2.newestMin >= 0) cfg.bulkReadV2.newestMin = v2.newestMin;
      if (typeof v2.newestMax === "number" && v2.newestMax > 0) cfg.bulkReadV2.newestMax = v2.newestMax;
      if (typeof v2.accessPercent === "number" && v2.accessPercent > 0) cfg.bulkReadV2.accessPercent = v2.accessPercent;
      if (typeof v2.accessMin === "number" && v2.accessMin >= 0) cfg.bulkReadV2.accessMin = v2.accessMin;
      if (typeof v2.accessMax === "number" && v2.accessMax > 0) cfg.bulkReadV2.accessMax = v2.accessMax;
    }

    // Resolve char limits: explicit array > linear endpoints > default
    if (Array.isArray(memoryRaw.maxCharsPerLevel) && memoryRaw.maxCharsPerLevel.length >= 1) {
      const levels = memoryRaw.maxCharsPerLevel as number[];
      if (levels.every((n: unknown) => typeof n === "number" && n > 0)) {
        const padded = [...levels];
        while (padded.length < cfg.maxDepth) padded.push(padded[padded.length - 1]);
        cfg.maxCharsPerLevel = padded.slice(0, cfg.maxDepth);
      }
    } else if (typeof memoryRaw.maxL1Chars === "number" || typeof memoryRaw.maxLnChars === "number") {
      const l1 = typeof memoryRaw.maxL1Chars === "number" ? memoryRaw.maxL1Chars : DEFAULT_CONFIG.maxCharsPerLevel[0];
      const ln = typeof memoryRaw.maxLnChars === "number" ? memoryRaw.maxLnChars : DEFAULT_CONFIG.maxCharsPerLevel[DEFAULT_CONFIG.maxCharsPerLevel.length - 1];
      cfg.maxCharsPerLevel = linearLimits(l1, ln, cfg.maxDepth);
    } else {
      cfg.maxCharsPerLevel = linearLimits(
        DEFAULT_CONFIG.maxCharsPerLevel[0],
        DEFAULT_CONFIG.maxCharsPerLevel[DEFAULT_CONFIG.maxCharsPerLevel.length - 1],
        cfg.maxDepth
      );
    }

    // Parse sync section (unified format only)
    if (syncRaw && syncRaw.serverUrl && syncRaw.userId && syncRaw.salt) {
      cfg.sync = {
        serverUrl: syncRaw.serverUrl,
        userId: syncRaw.userId,
        salt: syncRaw.salt,
        token: syncRaw.token,
        syncSecrets: syncRaw.syncSecrets !== undefined ? syncRaw.syncSecrets : true,
        lastPushAt: syncRaw.lastPushAt ?? null,
        lastPullAt: syncRaw.lastPullAt ?? null,
      };
    }

    return cfg;
  } catch (e) {
    console.error(`[hmem] Failed to parse hmem.config.json: ${e}. Using defaults.`);
    return { ...DEFAULT_CONFIG, prefixes: { ...DEFAULT_PREFIXES }, prefixDescriptions: { ...DEFAULT_PREFIX_DESCRIPTIONS }, bulkReadV2: { ...DEFAULT_CONFIG.bulkReadV2 } };
  }
}
